<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
      <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1"/>
      <PackageVersion Include="Asp.Versioning.OpenApi" Version="10.2.3"/>
      <PackageVersion Include="Aspire.Hosting.Azure.ServiceBus" Version="13.5.3"/>
      <PackageVersion Include="Aspire.Hosting.Keycloak" Version="13.5.3-preview.1.26425.3"/>
      <PackageVersion Include="Dapper" Version="2.1.86"/>
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageVersion Include="MassTransit.Abstractions" Version="9.2.1"/>
      <PackageVersion Include="MassTransit.Azure.ServiceBus.Core" Version="9.2.1"/>
      <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12"/>
      <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.13"/>
      <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
      <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12"/>
      <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12"/>
      <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12"/>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageVersion Include="Quartz" Version="4.1.0"/>
      <PackageVersion Include="Refit.HttpClientFactory" Version="15.2.0"/>
      <PackageVersion Include="Scalar.AspNetCore" Version="2.17.3"/>
      <PackageVersion Include="Scrutor" Version="7.0.0"/>
      <PackageVersion Include="Serilog" Version="4.4.0"/>
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageVersion Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0"/>
      <PackageVersion Include="SerilogTimings" Version="3.1.0"/>
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.32.0.713" />
  </ItemGroup>
</Project>