<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\Fcmb.Assessment.CSharp.Common.Application\Fcmb.Assessment.CSharp.Common.Application.csproj" />
      <ProjectReference Include="..\..\..\Common\Fcmb.Assessment.CSharp.Common.Infrastructure\Fcmb.Assessment.CSharp.Common.Infrastructure.csproj" />
    </ItemGroup>

</Project>
