<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\Fcmb.Assessment.CSharp.Common.Infrastructure\Fcmb.Assessment.CSharp.Common.Infrastructure.csproj" />
        <ProjectReference Include="..\Fcmb.Assessment.CSharp.Modules.Users.Presentation\Fcmb.Assessment.CSharp.Modules.Users.Presentation.csproj"/>
    </ItemGroup>

</Project>
