<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Fcmb.Assessment.CSharp.Common.Domain\Fcmb.Assessment.CSharp.Common.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Scrutor"/>
  </ItemGroup>
</Project>
