<Project Sdk="Aspire.AppHost.Sdk/13.5.1">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AspireUseCliBundle>true</AspireUseCliBundle>
        <UserSecretsId>945a9ef8-95c1-4ff2-83bd-e302f7775c12</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\API\Fcmb.Assessment.CSharp.Api\Fcmb.Assessment.CSharp.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Keycloak"/>
    </ItemGroup>

</Project>
